spring.application.name=portfolio
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
spring.datasource.username=root
spring.datasource.password=4CB23CB014

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# DevTools live-reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true